### PR TITLE
[I18N][14.0] project: Fix translation

### PR DESCRIPTION
**Pull request by duyquyen96**
Description of the issue/feature this PR addresses:[ [i18n] project: sửa dịch của module project](https://viindoo.com/web#cids=1&menu_id=777&action=1074&active_id=6&model=viin.helpdesk.ticket&view_type=form&id=52401)

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by duyquyen96** [comment]
@viinbot rebuild

**Comment by duyquyen96** [comment]
@viinbot rebase

**Comment by duyquyen96** [comment]
@viinbot rebuild

**Comment by royle-vietnam** [comment]
@viinbot r+

**Comment by royle-vietnam** [comment]
@viinbot fwd up

**Pull request merged**
