### PR TITLE
[I18N][15.0] stock translation report deliveryslip

### PR DESCRIPTION
**Pull request by ngochung207**
Description of the issue/feature this PR addresses:

[Ticket 10165](https://viindoo.com/web#id=10165&menu_id=89&model=helpdesk.ticket&view_type=form)
Current behavior before PR:

Desired behavior after PR is merged:

https://user-images.githubusercontent.com/11542778/211702501-586071cd-c51b-450a-964b-69e04b116d78.mp4

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by vietphuong97** [comment]
Anh @royleviindoo  merge giúp em pr này nhé.

**Comment by NguyenThaiHa-June** [comment]
@ngochung207 : a ơi. Runbot tèo rồi. Anh check nhá.

**Comment by ngochung207** [comment]
@royleviindoo em xem giúp anh PR này nhé.
cc @NguyenThaiHa-June

**Comment by ngochung207** [comment]
@royleviindoo em xem giúp anh PR này nhé
cc: @NguyenThaiHa-June @vietphuong10

**Pull request merged**
