### PR TITLE
Merge from upstream 16 20240102 01

### PR DESCRIPTION
**Pull request by daiduongnguyen-odoo**
Depends:

- [x] https://github.com/Viindoo/tvtmaaddons/pull/10029
- [x] https://github.com/Viindoo/tvtmaaddons/pull/10026
- [x] https://github.com/Viindoo/tvtmaaddons/pull/10031
- [x] https://github.com/Viindoo/tvtmaaddons/pull/10038

This would help fix some tickets, and also causing some dead test XD

Video (update 05/01/2024)

https://github.com/Viindoo/odoo/assets/56789189/f37a222f-72b4-41ec-9eb7-ef59d164f2e3

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by daiduongnguyen-odoo** [comment]
@royle-viindoo Odoo mới thêm module `l10n_be_pos_sale` nên a bỏ giúp em nó ra khỏi runbot ạ, vì nó tạo cty và gắn tiền tệ EUR vào công ty đó, ở test https://github.com/Viindoo/tvtmaaddons/blob/53f181222d755b5c1ee39e50c5039b429a358e27/to_odoo_module/tests/test_apps_market.py#L42 thì đang có quả `action_archive` tiền tệ đó nên lỗi

**Comment by daiduongnguyen-odoo** [comment]
@viinbot rebuild

**Comment by daiduongnguyen-odoo** [comment]
@royle-viindoo E đã merge upstream lại và update video cũng như các PR depends để nó đươc xanh ạ

**Comment by daiduongnguyen-odoo** [comment]
@viinbot rebuild

**Comment by royle-vietnam** [comment]
@viinbot rebuild

**Pull request merged**
