### PR TITLE
Merged from upstream 16 230812 01

### PR DESCRIPTION
**Pull request by davidtranhp**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by davidtranhp** [comment]
@viinbot rebuild

**Comment by davidtranhp** [comment]
@royleviindoo 
Selection_412
có nhiều PR dính lỗi này

**Comment by royle-vietnam** [comment]
> @royleviindoo có nhiều PR dính lỗi này

vâng ạ, để em cho 1 bạn xử lý ạ

**Comment by royle-vietnam** [comment]
@locdang8 em xử lỗi runbot này nhé
```
odoo.addons.mrp.tests.test_order: FAIL: TestMrpOrder.test_compute_tracked_time_1
Traceback (most recent call last):
File "/data/build/rb-c53b137-188372/addons/mrp/tests/test_order.py", line 2373, in test_compute_tracked_time_1
self.assertEqual(production.workorder_ids[0].duration_expected, 10.0, "Duration is now 0+0+1*10")
AssertionError: 15.0 != 10.0 : Duration is now 0+0+1*10
```

**Comment by locdang8** [comment]
> @locdang8 em xử lỗi runbot này nhé
> 
> ```
> odoo.addons.mrp.tests.test_order: FAIL: TestMrpOrder.test_compute_tracked_time_1
> Traceback (most recent call last):
> File "/data/build/rb-c53b137-188372/addons/mrp/tests/test_order.py", line 2373, in test_compute_tracked_time_1
> self.assertEqual(production.workorder_ids[0].duration_expected, 10.0, "Duration is now 0+0+1*10")
> AssertionError: 15.0 != 10.0 : Duration is now 0+0+1*10
> ```

vâng a

**Comment by locdang8** [comment]
> @locdang8 em xử lỗi runbot này nhé
> 
> ```
> odoo.addons.mrp.tests.test_order: FAIL: TestMrpOrder.test_compute_tracked_time_1
> Traceback (most recent call last):
> File "/data/build/rb-c53b137-188372/addons/mrp/tests/test_order.py", line 2373, in test_compute_tracked_time_1
> self.assertEqual(production.workorder_ids[0].duration_expected, 10.0, "Duration is now 0+0+1*10")
> AssertionError: 15.0 != 10.0 : Duration is now 0+0+1*10
> ```

lỗi lúc có lúc không do lỗi odoo kết quả sắp xếp search chưa chính xác, e thấy họ đã xử lý ở commit này https://github.com/odoo/odoo/pull/131815/commits/8a5ec953a775faf8942e855be7bce678182c08f7 nhưng chưa merge

**Pull request merged**
